version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: django
      MYSQL_USER: djilali
      MYSQL_PASSWORD: 123123
    ports:
      - "3306:3306"

  djangoserver:
    container_name: djangoserver
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:123123@db:3306/django
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build: .
    command: celery -A project worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql://root:123123@db:3306/django

  

networks:
  default:
    driver: bridge